pkg/api/connection/mechanisms/common/constants.go, pkg/api/connection/mechanisms/kernel/constants.go, pkg/api/connection/mechanisms/kernel/helpers.go, pkg/api/connection/mechanisms/memif/helpers.go
https://github.com/golang/go/wiki/CodeReviewComments#initialisms
Change does not touch autogenerated things but we probably should also update service name in https://github.com/networkservicemesh/api/blob/0623273c4e70ea80e64087a7a9ff217c9dbdb358/pkg/api/registry/registry.proto#L75
Signed-off-by: Piotr Skamruk <piotr.skamruk@gmail.com>
=> Fix initialisms

.github/workflows/update-sdk.yaml
Turns out that sometimes the google go module proxy isn't
quick about getting updated from github.com.  Since obviously
we *want* to get this right, we use  GOPROXY=direct to force
it to go to the direct source.
=> Use  GOPROXY=direct for update-sdk.yaml

pkg/api/connection/mechanisms/sriovkernel/constants.go, pkg/api/connection/mechanisms/sriovkernel/helpers.go, pkg/api/connection/mechanisms/sriovuserspace/constants.go, pkg/api/connection/mechanisms/sriovuserspace/helpers.go
Add SRIOV mechanisms:
* SRIOV_KERNEL for kernel network stack based interfaces
* SRIOV_USERSPACE mechanism for devices using accelerated userspace
datapath (e.g. DPDK)
Signed-off-by: Przemyslaw Lal <przemyslawx.lal@intel.com>
=> Add SRIOV mechanisms

pkg/api/networkservice/mechanisms/vfio/constants.go, pkg/api/networkservice/mechanisms/vfio/helpers.go
Putting this out there as a draft for discussion on naming.  I look to folks who know this space better to tell me whether this is a good idea or a bad one :)
=> Rename SRIOV_USERSPACE to vfio.

pkg/api/networkservice/mechanisms/vxlan/helpers.go
Replace m.Type with m.GetType() to make us panic safe.
=> Small fix to mechanisms/vxlan

.github/workflows/ci.yaml
Setup protoc action https://github.com/arduino/setup-protoc has moved from `arduino/actions/setup-protoc@master` to `arduino/setup-protoc@master`
=> Update setup-protoc step for job 'Check protobuf generation'

pkg/api/networkservice/connection_helpers.go
Fixes:
```go
panic: runtime error: index out of range [4294967295] with length 1 [recovered]
panic: runtime error: index out of range [4294967295] with length 1
```
=> fix: path segments helper functions can produce uint overflowing

pkg/api/networkservice/mechanisms/wireguard/helpers.go
=> fix: wrong base for wireguard port parsing

pkg/api/networkservice/mechanisms/common/constants.go, pkg/api/networkservice/mechanisms/vxlan/constant.go, pkg/api/networkservice/mechanisms/vxlan/helpers.go, pkg/api/networkservice/mechanisms/wireguard/constant.go
Also cleaned up wireguard to use common.* parameters when possibe.
Signed-off-by: Ed Warnicke <hagbard@gmail.com>
=> Unify Src/Dst Port handling across remote mechanisms

.github/workflows/release.yaml
By default actions/create-release@v1 creates tags based always on the default branch. It can affect NSM release.
Create a tag on a required branch before doing the release.
=> fix: push tag on a release branch before creating release

pkg/api/networkservice/mechanisms/kernel/helpers.go
Issue: https://github.com/networkservicemesh/sdk-vpp/issues/254
Generation moved to sdk: https://github.com/networkservicemesh/sdk/pull/1014
=> Remove kernel interface name generation

pkg/api/networkservice/mechanisms/kernel/constants.go, pkg/api/networkservice/mechanisms/kernel/helpers.go
Updates for kernel mechanism helper: 'supportsVlan' and 'vlan' parameters added
This would be an alternative solution instead related #97 and #98
Signed-off-by: Laszlo Kiraly <laszlo.kiraly@est.tech>
=> VLAN support; Added VLAN support to kernel mechanism

pkg/api/networkservice/mechanisms/common/constants.go, pkg/api/networkservice/mechanisms/kernel/constants.go, pkg/api/networkservice/mechanisms/kernel/helpers.go, pkg/api/networkservice/mechanisms/vfio/constants.go, pkg/api/networkservice/mechanisms/vfio/helpers.go
Adds SR-IOV token ID mechanism parameter for kernel, VFIO mechanisms.
Actually moves it from `sdk-sriov` to more relevant place.
https://github.com/networkservicemesh/sdk-sriov/blob/9a5f775aa79d492447aa58867b0a3218be78ff48/pkg/networkservice/common/resourcepool/common.go#L35-L36
Needed for networkservicemesh/sdk-vpp#314.
=> [sdk-vpp#314] Add SR-IOV token ID mechanism parameter for kernel, VFIO mechanisms

pkg/api/networkservice/mechanisms/common/constants.go, pkg/api/networkservice/mechanisms/kernel/constants.go, pkg/api/networkservice/mechanisms/kernel/helpers.go, pkg/api/networkservice/mechanisms/memif/constants.go, pkg/api/networkservice/mechanisms/memif/helpers.go
Modifies `memif` helper:
1. Adds `SetSocketFilename`.
2. Replaces `{Get|Set}SocketFileURL` with `{Get|Set}NetNSURL`.
networkservicemesh/sdk-vpp#370
=> [sdk-vpp#370] Change memif to work with abstract sockets

pkg/api/networkservice/mechanisms/memif/helpers.go
Continues https://github.com/networkservicemesh/api/pull/113.
networkservicemesh/sdk-vpp#370
=> [sdk-vpp#357] Add missed helper methods for memif

.github/workflows/ci.yaml, .github/workflows/release.yaml, .github/workflows/update-dependent-repositories-gomod.yaml, .golangci.yml, go.mod, pkg/api/ipam/gen.go, pkg/api/networkservice/gen.go, pkg/api/registry/gen.go
=> bump: update go to v1.18.1

pkg/api/networkservice/mechanisms/kernel/helpers.go
Signed-off-by: Sergey Shlyanin <sergey.shlyanin@xored.com>
=> Fix getting iptables rules

pkg/api/networkservice/mechanisms/ipsec/constant.go, pkg/api/networkservice/mechanisms/ipsec/doc.go, pkg/api/networkservice/mechanisms/ipsec/helpers.go
Issue: https://github.com/networkservicemesh/sdk-vpp/issues/638
**_Please note:_** IKEv2 uses 500 UDP port for key exchange - https://www.rfc-editor.org/rfc/rfc5996
This is a standard port, so it's not supposed to be in the api.
The current PR has only a port for data transfer (it is 4500 by default)
=> Add IPSec remote mechanism

pkg/api/networkservice/connection_helpers.go, pkg/api/networkservice/connection_helpers_test.go
https://github.com/networkservicemesh/api/issues/164
=> Fix Connection Selector

.github/workflows/release.yaml
https://github.com/networkservicemesh/.github/issues/58
=> Create releases with Github CLI

pkg/api/networkservice/connection_helpers.go, pkg/api/networkservice/connectioncontext_helpers.go, pkg/api/networkservice/helpers.go, pkg/api/networkservice/ipcontext_helpers.go, pkg/api/networkservice/mechanism_helpers.go, pkg/api/networkservice/mechanisms/kernel/helpers.go, pkg/api/networkservice/path_helpers.go
https://github.com/networkservicemesh/api/issues/143
=> Delete unused helper functions

.github/workflows/update-dependent-repositories-gomod.yaml
Fixes 
```
Run GOPRIVATE=github.com/networkservicemesh go get -u github.com/networkservicemesh/api@main
go: downloading github.com/networkservicemesh/api v1.14.2-0.20241205110710-[8](https://github.com/networkservicemesh/api/actions/runs/12178499185/job/33968627597#step:7:9)27a859925b7
go: upgraded github.com/networkservicemesh/api v1.13.4-0.20240815101554-fdbfcd84fd0e => v1.14.2-0.20241205110710-827a85[9](https://github.com/networkservicemesh/api/actions/runs/12178499185/job/33968627597#step:7:10)925b7
go: go.mod file indicates go 1.23, but maximum version supported by tidy is 1.20
Error: Process completed with exit code 1.
```
https://github.com/networkservicemesh/api/actions/runs/12178499185
=> qfix: update go to v1.23.3 for update-dependent-repositories-gomod.yaml

.github/dependabot.yml, .github/workflows/automerge.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
This PR enables Dependabot in the repository to automatically check GitHub Actions versions weekly and create pull requests for any outdated dependencies found.
=> Enable dependabot for updating github actions

.github/workflows/automerge.yaml
This PR removes Dependabot actor from the automerge workflow. Dependabot alerts create PRs that are not eligible for automerge, making this adjustment necessary.
=> Exclude dependabot from automerge due to dependabot alerts
