.github/workflows/update-sdk.yaml
A few notes: we are only updating sdk/ here, because sdk/ updates
its downstreams.
=> Add Github Action to update sdk from api.

.golangci.yml, go.sum, pkg/api/networkservice/connection_helpers.go, pkg/api/networkservice/connectioncontext_helpers.go, pkg/api/networkservice/mechanisms/common/helpers.go, pkg/api/networkservice/mechanisms/sriovkernel/constants.go, pkg/api/networkservice/mechanisms/sriovkernel/helpers.go, pkg/api/networkservice/mechanisms/sriovuserspace/constants.go, pkg/api/networkservice/mechanisms/sriovuserspace/helpers.go, pkg/api/networkservice/mechanisms/srv6/helpers.go, pkg/api/networkservice/path_helpers.go
https://github.com/networkservicemesh/api/pull/10 brought in SRIOV changes
after the simplification from:
https://github.com/networkservicemesh/api/pull/12
and initialism fixes from:
https://github.com/networkservicemesh/api/pull/11
This fixes those.
=> Fix what came in with SRIOV to match simplification

.github/workflows/ci.yaml, go.mod, go.sum, pkg/api/networkservice/connection.pb.go, pkg/api/networkservice/networkservice.pb.go, pkg/api/registry/registry.pb.go
Signed-off-by: Denis Tingajkin <denis.tingajkin@xored.com>
=> Update protobuf version and re-gen proto files

pkg/api/networkservice/mechanisms/wireguard/constant.go, pkg/api/networkservice/mechanisms/wireguard/doc.go, pkg/api/networkservice/mechanisms/wireguard/helpers.go
https://github.com/networkservicemesh/api/issues/27
=> Add wireguard remote mechanism to API

pkg/api/networkservice/mechanisms/srv6/helpers.go
https://github.com/networkservicemesh/api/issues/30
=> Mechanism srv6 should return zero value for parameters instead of error

pkg/api/networkservice/mechanisms/vxlan/helpers.go
https://github.com/networkservicemesh/api/issues/29
=>  Mechanism vxlan should return zero value for parameters instead of error

pkg/api/helpers.go, pkg/api/networkservice/helpers.go, pkg/api/registry/helpers.go
This is useful for grpc.HealhChecks
=> Add ServiceName() functino to retrieve ServiceNames from implementations

pkg/api/registry/helpers.go
Based on https://github.com/networkservicemesh/sdk/pull/298#discussion_r440202042
=> Add stream helper functions for registry

pkg/api/registry/helpers.go
=> Add stream channel helper functions

pkg/api/networkservice/mechanisms/memif/helpers.go
Signed-off-by: Denis Tingajkin <denis.tingajkin@xored.com>
=> refactor: Add helper function for instancing memif mechanism

.github/workflows/update-dependent-repositories-gomod.yaml
=> fix: api cannot update sdk go.mod version on merge

pkg/api/networkservice/ipcontext_helpers.go
Signed-off-by: Ed Warnicke <hagbard@gmail.com>
=> Add IPContext helper

.github/workflows/ci.yaml, .golangci.yml
=> Update golangci linter to v1.34.0

pkg/api/registry/helpers.go
=> Improve read channel registry functions to use context

.github/workflows/ci.yaml, pkg/api/networkservice/mechanisms/kernel/constants.go
All other mechanisms use short mechanism style names.
These constant can be used for parsing NSM URL.
=> refactor: change mechanism kernel value

pkg/api/networkservice/mechanisms/wireguard/constant.go, pkg/api/networkservice/mechanisms/wireguard/helpers.go
=> New wireguard api parameters

.github/workflows/ci.yaml
=> fix: gogenerate job actually doesn't fail ci in case it has diff

.github/workflows/automerge.yaml, .github/workflows/ci.yaml, .github/workflows/update-dependent-repositories-gomod.yaml, go.mod
https://github.com/networkservicemesh/sdk/issues/819
=> fix: Automerge job is not working

.github/workflows/update-dependent-repositories-gomod.yaml
=> fix: condition for update deps job is wrong

.github/workflows/automerge.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/update-dependent-repositories-gomod.yaml
Signed-off-by: Ed Warnicke <hagbard@gmail.com>
=> Migrate api from 'master' default branch to 'main'

pkg/api/networkservice/mechanisms/common/constants.go, pkg/api/networkservice/mechanisms/vxlan/constant.go, pkg/api/networkservice/mechanisms/vxlan/helpers.go, pkg/api/networkservice/mechanisms/vxlan/helpers_test.go, pkg/api/networkservice/mechanisms/wireguard/constant.go
=> refactor: add DstOriginalIP and remove DstExternalIP

pkg/api/networkservice/mechanisms/wireguard/constant.go, pkg/api/networkservice/mechanisms/wireguard/helpers.go
=> Add wireguard mtu field

.github/workflows/ci.yaml, .github/workflows/release.yaml
https://github.com/networkservicemesh/release/issues/1
=> feat: Add release github actions

.github/workflows/release.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
=> fix: Skip deleting exist release for a while

.github/workflows/release.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
=> Return back deleting existing release on push in release/** branches 

.github/workflows/automerge.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
Signed-off-by: Mikhail Avramenko <avramenkomihail15@gmail.com>
part of https://github.com/networkservicemesh/cmd-template/issues/64
=> Changed NSMbot version

pkg/api/networkservice/mechanisms/vlan/constant.go, pkg/api/networkservice/mechanisms/vlan/helpers.go
Signed-off-by: Laszlo Kiraly <laszlo.kiraly@est.tech>
=> Add vlan remote mechanism support

pkg/api/networkservice/labels/sriov/constants.go
Signed-off-by: Dimitrios Markou <dimitrios.markou@est.tech>
=> Create SR-IOV related constants

pkg/api/networkservice/mechanisms/kernel/constants.go, pkg/api/networkservice/mechanisms/kernel/helpers.go
Signed-off-by: Sergey Shlyanin <sergey.shlyanin@xored.com>
#133
=> Add IP Tables ipv4 chains/rules template to kernel mechanism

pkg/api/networkservice/mechanisms/kernel/helpers.go
Signed-off-by: Sergey Shlyanin <sergey.shlyanin@xored.com>
=> Modify kernel mechanism to save iptables rules as an array

pkg/api/networkservice/mechanisms/kernel/helpers.go
FIxes a big problem in template code https://github.com/networkservicemesh/cmd-nse-istio-proxy/blob/fa60f4a442a44677b30486a01f9973b10668745e/main.go#L336-L339
Related to https://github.com/networkservicemesh/api/issues/133
=> qfix: pass only ip addresses into template

.github/workflows/automerge.yaml
Signed-off-by: Nikita Skrynnik <nikita.skrynnik@xored.com>
=> Add automerge reusable workflow

pkg/api/networkservice/connection.proto
https://github.com/networkservicemesh/api/issues/169
=> Add descriptions for Connection States and ConnectionEvent Types

.github/workflows/update-dependent-repositories-gomod.yaml
https://github.com/networkservicemesh/.github/issues/67
=> Remove some triggers from Update dependent repositories

pkg/api/networkservice/ipcontext_helpers.go
https://github.com/networkservicemesh/integration-k8s-kind/pull/1026
=> Revert changes in `strToIPNet` func
